/**
 * Security Rule Verification Test Suite
 * Tests 12 Dirty Dozen payloads against Firestore security invariants.
 */

export const DIRTY_DOZEN_PAYLOADS = [
  {
    id: 'payload_1',
    description: 'Rogue Path Injection / ID Poisoning (Oversized Document ID)',
    collection: 'invoices',
    docId: 'A'.repeat(500),
    data: { id: 'bad', invoiceNo: 'INV-001', type: 'general', mode: 'sales' },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 'payload_2',
    description: 'Unauthenticated Write Attempt to Core Invoices Collection',
    collection: 'invoices',
    docId: 'inv-unauth-1',
    data: { id: 'inv-unauth-1', invoiceNo: 'INV-999', type: 'general', mode: 'sales', partyName: 'Hacker', subtotal: 100, grandTotal: 100 },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 'payload_3',
    description: 'Negative Price / Negative Quantity Invariant Breach',
    collection: 'stock',
    docId: 'stk-bad-rate',
    data: { id: 'stk-bad-rate', category: 'code', nameBn: 'টেস্ট', code: 'T-1', quantity: -50, unit: 'pcs', purchaseRate: -1000 },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 'payload_4',
    description: 'Shadow Key / Privilege Escalation Ghost Field',
    collection: 'invoices',
    docId: 'inv-shadow-1',
    data: { id: 'inv-shadow-1', invoiceNo: 'INV-10', type: 'general', mode: 'purchase', partyName: 'Party', subtotal: 100, grandTotal: 100, isAdmin: true, role: 'superadmin' },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 'payload_5',
    description: 'Oversized Text Denial-of-Wallet Payload',
    collection: 'parties',
    docId: 'pty-huge-note',
    data: { id: 'pty-huge-note', name: 'Huge', phone: '01700000000', address: 'X', type: 'buyer', notes: 'Z'.repeat(100000) },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 'payload_6',
    description: 'Invalid Enum Value Injection on Stock Category',
    collection: 'stock',
    docId: 'stk-invalid-enum',
    data: { id: 'stk-invalid-enum', category: 'malicious_cat', nameBn: 'টেস্ট', code: 'C-01', quantity: 10, unit: 'pcs', purchaseRate: 100 },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 'payload_7',
    description: 'Invalid Invoice Mode Spoofing',
    collection: 'invoices',
    docId: 'inv-invalid-mode',
    data: { id: 'inv-invalid-mode', invoiceNo: 'INV-MODE', type: 'general', mode: 'root_override', partyName: 'Fake', subtotal: 50, grandTotal: 50 },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 'payload_8',
    description: 'Attendance Negative Overtime Hours Tampering',
    collection: 'attendance',
    docId: 'att-neg-ot',
    data: { id: 'att-neg-ot', staffId: 'stf-1', staffName: 'Staff', date: '2026-09-24', status: 'present', otHours: -99, otAmount: -5000 },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 'payload_9',
    description: 'Unauthenticated Deletion of Financial Audit Trail',
    collection: 'invoices',
    docId: 'inv-1',
    data: null,
    operation: 'delete',
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 'payload_10',
    description: 'Unauthenticated Overwrite of Enterprise Company Profile',
    collection: 'company',
    docId: 'main',
    data: { name: 'Hijacked Company', email: 'scam@phish.com', address: 'Unknown' },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 'payload_11',
    description: 'Arbitrary Undefined Collection Root Injection',
    collection: 'system_backdoor',
    docId: 'exploit',
    data: { payload: 'execute' },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 'payload_12',
    description: 'Type Confusion / Non-String Array Spoof on Primary Key',
    collection: 'parties',
    docId: 'pty-type-confuse',
    data: { id: ['hacked', 'array'], name: 12345, phone: true, address: {}, type: 'supplier' },
    expectedResult: 'PERMISSION_DENIED',
  },
];
